//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id_post { get; set; }
        public string text_post { get; set; }
        public string path_img { get; set; }
    }
}
