//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reacciones_post
    {
        public int id_reacciones_post { get; set; }
        public Nullable<int> post_usuario_id { get; set; }
        public Nullable<int> amigo_id { get; set; }
        public Nullable<int> gusta { get; set; }
        public Nullable<int> divierte { get; set; }
        public Nullable<int> asombra { get; set; }
        public Nullable<int> enamora { get; set; }
        public Nullable<int> entristece { get; set; }
        public Nullable<int> enoja { get; set; }
    }
}
