//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_post
    {
        public int id_usuario_post { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> reacciones_id { get; set; }
        public Nullable<System.DateTime> fecha_post { get; set; }
    }
}
